### ISSUE TITLE
[Relay Spam] Spam to our relays is still visible across the network

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nosrelay#8]
Steps to reproduce: 
1. On Monday I wrote the following note:  note1zhj9m7zt25rpwhw0rsn0tqpl3nzd0kjyc7kuptpkgtwt6xlfe3tqmf376k
2. I received replyguy notes from 4 relays: 

![Image](https://github.com/user-attachments/assets/39e3648c-8247-4a4e-98f3-f7393746f18c)

3. Go to the note and look at the replies that are remaining on the network. Only the one from dwebcamp.nos.social is still visible. 

Can check out a similar instance with this note: note164xgedgema37xtmmq5ucxl94d0pgl0mzpdd88r36r3ne2p8h8mzq99naha
i received replies from 4-5 relays and the other 2 replies are gone and now on the nos.social replies remain. 

Expected: Spam should be removed from ALL of our relays and should not still be visible in the network.

**Comment by dcadenas** [comment]
I will move this to in progress and point to a new spam measures issue.

**Comment by mplorentz** [comment]
From our meeting today: let's also do a one-time delete of all data from people named ReplyGuy or ReplyGal.
